{
 "title": "Murcia Weather",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Temperature, Clouds, Precipitation and Wind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Murcia Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT temp AS \"Temperature\", app_temp AS \"Apparent Temperature\", datetime AS time FROM weather_data "
    }
   ]
  },
  {
   "title": "Apparent Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT app_temp FROM weather_data"
    }
   ]
  },
  {
   "title": "Murcia Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT rh AS \"Relative Humidity\", datetime AS \"Time\" FROM weather_data"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT rh FROM weather_data" }
   ]
  },
  {
   "title": "Murcia Clouds Coverage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT clouds, datetime AS Time FROM weather_data"
    }
   ]
  },
  {
   "title": "Clouds Coverage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT clouds FROM weather_data"
    }
   ]
  },
  {
   "title": "Murcia Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "targets": [
    {
     "rawSql": "SELECT precip AS \"Precipitation\", datetime AS \"Time\" FROM weather_data"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT precip FROM weather_data"
    }
   ]
  },
  {
   "title": "Murcia Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT wind_spd AS \"Wind Speed\", gust AS \"Wind Gust Speed\", datetime AS \"Time\" FROM weather_data"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_spd FROM weather_data"
    }
   ]
  },
  {
   "title": "Solar Radiation and Air Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "Murcia Radiation And Irradiance (W/m^2)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT solar_rad AS \"Solar Radiation\", dni AS \"Direct Normal Solar Irradiance\", dhi AS \"Diffuse Horizontal Solar Irradiance\", datetime AS Time FROM weather_data "
    }
   ]
  },
  {
   "title": "Murcia Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT aqi AS \"Air Quality\", datetime AS Time FROM weather_data"
    }
   ]
  },
  { "title": "Weather Alerts (14 days)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Murcia Weather Alerts And Description",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT effective_utc AS \"Date\", title AS \"Title\", regions AS \"Regions\", description AS \"Description\" FROM weather_alerts WHERE DATE(effective_utc) >= CURRENT_DATE - INTERVAL '14 days' ORDER BY effective_utc DESC "
    }
   ]
  },
  { "title": "Historical Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(temp) AS \"Max\", MIN(temp) AS \"Min\" FROM weather_data"
    }
   ]
  },
  {
   "title": "Apparent Temperature",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(app_temp) AS \"Max\", MIN(app_temp) AS \"Min\" FROM weather_data"
    }
   ]
  },
  {
   "title": "Max Precipitation",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "mm/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(precip) AS \"Max Precipitation\" FROM weather_data"
    }
   ]
  },
  {
   "title": "Max Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(wind_spd) AS \"Max Wind Speed\" FROM weather_data"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(aqi) AS \"Max\", MIN(aqi) AS \"Min\" FROM weather_data LIMIT 50 "
    }
   ]
  }
 ]
}